# Generated by Django 2.1.5 on 2019-06-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('bTime', models.DateTimeField()),
                ('price', models.FloatField(max_length=10)),
                ('amount', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('veg', models.FloatField(max_length=255)),
                ('meat', models.FloatField(max_length=255)),
                ('egg', models.FloatField(max_length=255)),
                ('melon', models.FloatField(max_length=255)),
                ('cooked', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('amount', models.IntegerField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='salerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Student'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Window'),
        ),
    ]
