# Generated by Django 2.1.5 on 2019-06-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeftFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftNum', models.FloatField(max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Food')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmaterial',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.Food'),
        ),
        migrations.AlterField(
            model_name='foodmaterial',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
